### ISSUE TITLE
Fatal error: Class undefined: Composer\Installer\PackageEvents / MergePlugin.php on line 142

### ISSUE THREAD

**Issue by mwjames** [wikimedia/composer-merge-plugin#42]
Encountered 
```
Installing dependencies (including require-dev)
  - Installing wikimedia/composer-merge-plugin (v1.2.0)
    Downloading: connection...    Failed to download wikimedia/composer-merge-plugin from dist: The "https://api.github.com/repos/wikimedia/composer-merge-plugin/zipball/fa2079fa0bca55a9d053bfd0fb75331423260c18" file could not be downloaded (HTTP/1.1 403 Forbidden)
    Now trying to download from source
- Installing wikimedia/composer-merge-plugin (v1.2.0)
    Cloning fa2079fa0bca55a9d053bfd0fb75331423260c18
Fatal error: Class undefined: Composer\Installer\PackageEvents in /home/travis/build/SemanticMediaWiki/mw/vendor/wikimedia/composer-merge-plugin/src/MergePlugin.php on line 142
```
on https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/68637285

**Comment by bd808** [comment]
The `Composer\Installer\PackageEvents` class was introduced in https://github.com/composer/composer/commit/3efed220a6c9fd6e4a13ea806879e124941c9fc7 on 2015-02-23. The version in that Travis run was a couple weeks older (https://github.com/composer/composer/commit/1d8f05f1dd0e390f253f79ea86cd505178360019) and gave the notorious "older than 30 days" warning.

The event names that were moved to  `Composer\Installer\PackageEvents` are still available in the `Composer\Script\ScriptEvents` class but they are all marked as deprecated. I didn't notice this when I introduced the new usage in 431020fa9a184583cf27e4f6e19746f613f954c0.

We haven't really established a Composer version compatibility threshold for this project yet. Until they finally get around to releasing a 1.0 version and start doing some kind of semantic versioning it's pretty hard to guess how hard to work to retain compatibility with older versions. Is it reasonable to try and support builds older than the latest tagged alpha (https://github.com/composer/composer/releases/tag/1.0.0-alpha10)?

**Comment by JeroenDeDauw** [comment]
Loose from theoretical niceness, I suggest to go with the pragmatic approach of at least attempting to retain compat with the Composer version used by TravisCI. (At least for releases of this plugin, not for master)

**Comment by bd808** [comment]
> I suggest to go with the pragmatic approach of at least attempting to retain compat with the Composer version used by TravisCI.

Not a horrible idea in theory. Do you know of any service or webpage that we can check easily to determine what version of Composer Travis has deployed at any given time? Based on my reading of https://github.com/travis-ci/travis-ci/issues/907 it sounds like they should be updating with each new worker refresh which is "sort of on a monthly schedule".

The failing test that started this thread however shows a version from 2015-02-11 being used during a test performed on 2015-06-28. Interestingly the full report from the test claims that the build image the the VM was build from was created on 2015-02-04 which is actually before the Composer version in use was available. That image creation date is almost 5 months before the test date as well which makes me think there is a strong emphasis on "sort of" in their monthly refresh cycle.

**Comment by bd808** [comment]
Now that Composer has released a stable 1.0.0 version, composer-merge-plugin v1.x will retain compatibility with it. When we can no longer be compatible with Composer 1.0.0 we will make a major version bump.
